language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  # This excludes OSX builds from the build matrix for gcc
  exclude:
    - os: osx
      compiler: gcc

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  - "if [ $CC = 'gcc' ]; then export CXX=g++; fi"
  - "if [ $CC = 'clang' ]; then export CXX=clang++; fi"
  - "sudo find / -name zlib.h"
  - "sudo find / -name zconf.h"
  # remove the `zlib.h` and `zconf.h` in system path to prevent implicit dependency 
  # and to reproduce #48 and #106
  - "sudo rm -f /usr/include/zlib.h"
  - "sudo rm -f /usr/include/zconf.h"
  - "sudo find / -name libz.a"
  # remove the `libz.a` in system path to prevent implicit dependency
  # and to reproduce #48
  - "sudo rm -f /usr/lib/x86_64-linux-gnu/libz.a"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install cmake; fi"

install:
  - "mkdir -p $TRAVIS_BUILD_DIR/build/scripts"
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "cmake $TRAVIS_BUILD_DIR/src"

script:
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "make -j3"
  # legacy binary tests
  - "make tests_htm"
  # (not quite everything, really)
  - "make tests_everything"
