#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.3.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015 CTP

init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\nupic-core

environment:
  matrix:
    # Must add either GCC or CLang here
    # i.e. - COMPILER_FAMILY: GNU
    - COMPILER_FAMILY: MSVC
      DEPLOY_TO_S3: 1
      DEPLOY_TO_NUGET: 1

skip_commits:
  # Add [av skip] to commit messages to skip AppVeyor building
  # Add [ci skip] to skip Travis and AppVeyor building
  message: /\[av skip\]/ 

#---------------------------------#
#       build configuration       #
#---------------------------------#

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

configuration: Release

install:
  - set REPO_DIR=c:\projects\nupic-core
  - mkdir %REPO_DIR%\build\
  - mkdir %REPO_DIR%\build\release
  - mkdir %REPO_DIR%\build\scripts
  - cd %REPO_DIR%\build\scripts
  # Need at least version 3.1.0 for the VS 2015 generator
  - ps: Start-FileDownload 'http://www.cmake.org/files/v3.1/cmake-3.1.0-win32-x86.zip'
  - ps: Write-Host '7z x cmake-3.1.0-win32-x86.zip'
  - ps: Start-Process -FilePath "7z" -ArgumentList "x -y cmake-3.1.0-win32-x86.zip" -Wait -Passthru
  - set PATH="%REPO_DIR%\build\scripts\cmake-3.1.0-win32-x86\bin";%PATH%
  - set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
  - echo %PATH%
  - cd %REPO_DIR%\build\scripts
  - set EXT_LIBS=%REPO_DIR%\external\windows64\lib
  - cmake %REPO_DIR%\src
     -G "Visual Studio 14 2015 Win64" -Wno-dev
     -DCMAKE_BUILD_TYPE=Release 
     -DCMAKE_INSTALL_PREFIX=..\Release
     -DLIB_STATIC_APR1_LOC=%EXT_LIBS%\apr-1.lib
     -DLIB_STATIC_APRUTIL1_LOC=%EXT_LIBS%\aprutil-1.lib
     -DLIB_STATIC_YAML_CPP_LOC=%EXT_LIBS%\yaml-cpp.lib
     -DLIB_STATIC_YAML_LOC=%EXT_LIBS%\yaml.lib
     -DLIB_STATIC_Z_LOC=%EXT_LIBS%\z.lib
     -DLIB_STATIC_CAPNP_LOC=%EXT_LIBS%\capnp.lib
     -DLIB_STATIC_KJ_LOC=%EXT_LIBS%\kj.lib

build_script:
  - cd %REPO_DIR%\build\scripts
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Release /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% gtest.vcxproj
  - msbuild %MSBuildOptions% nupic_core_solo.vcxproj
  - msbuild %MSBuildOptions% helloregion.vcxproj
  - msbuild %MSBuildOptions% prototest.vcxproj
  - msbuild %MSBuildOptions% py_region_test.vcxproj
  - msbuild %MSBuildOptions% cpp_region_test.vcxproj
  - msbuild %MSBuildOptions% unit_tests.vcxproj
  - set MSBuildOptions=/v:q /p:Configuration=Release /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% INSTALL.vcxproj

after_build:
  # Run the tests
  - cd %REPO_DIR%\build\release\bin
  - prototest 2>&1
  - cpp_region_test 1 2>&1
  - unit_tests --gtest_output=xml:unit_tests_report.xml 2>&1

  - cd %REPO_DIR%\build\release
  - set PROJECT_BUILD_ARTIFACTS_DIR=%REPO_DIR%\build\artifacts

  # NOTE: S3 deployment takes precedence when setting BUILD_ARTIFACTS
  - ps: >-
      if($env:DEPLOY_TO_NUGET -eq 1) {
        copy $env:REPO_DIR\Package.nuspec .
        nuget pack -version $env:APPVEYOR_BUILD_VERSION
        nuget push *.nupkg 30618afb-ecf6-4476-8e61-a5b823ad9892
        # NOTE: Push to nuget is here, rather than normal AV deployment
      }
      if($env:DEPLOY_TO_S3 -eq 1) {
        # This packages via CMakeList CPack settings (Tar.Gzip for SW upload)
        # msbuild $env:MSBuildOptions PACKAGE.vcxproj
        # Calling 7z twice achieves the same result
        7z a -ttar -y -bd nupic_core-$env:APPVEYOR_REPO_COMMIT-Windows64.tar .
        7z a -tgzip -y -bd ..\..\nupic_core-$env:APPVEYOR_REPO_COMMIT-Windows64.tar.gz nupic_core-$env:APPVEYOR_REPO_COMMIT-Windows64.tar
      }

test: off
 
# to disable deployment
#deploy: off

artifacts:
  - path: '**\*.tar.gz' # find all Gz(ip) packages recursively
    name: S3 package

deploy:

  # Amazon S3 deployment provider settings
  - provider: S3
    access_key_id:
      secure: AKIAIGHYSEHV3WFKOWNQ
    secret_access_key:
      secure: YhyY/6r2LNya8OZEmVOj+fv0lY5bBPqvy8MnsdLlptXa2uqwvezkCMNKiQ+wA+tOu+BS7VRRp86DhUqCpTZ3jUM2Mwdhud/Smq7D2X8vtZBiTVcOKfQcaypDE6Zu9Zp0SjMOSf6yiq6Ruu7D5QtZ4rtaq+5uPlvbgUXRZoZm0Po=
    bucket: "artifacts.numenta.org"
    region: us-west-2
    local-dir: "%PROJECT_BUILD_ARTIFACTS_DIR%"
    upload-dir: "numenta/nupic.core"
    skip_cleanup: true
    # Deploying on master branch
    on:
      #branch: master
      branch: 311-appveyor-s3-support
