# CircleCI Build Config
#   https://circleci.com/docs/2.0/configuration-reference/#section=configuration
#
# Targets:
#   - Max OS/X
#   - ARM64

version: 2
jobs:

  # job: Mac OS/X raw ("build-debug"). This job runs C++ tests in Debug mode (=with extra checks)
  osx-build-debug:
    macos:
      xcode: '11.0.0'
    working_directory: ~/numenta/htm.core
    parallelism: 1
    environment:
      XCODE_SCHEME: htm
      XCODE_WORKSPACE: htm
      ARCHFLAGS: -arch x86_64
    steps:
      # Machine Setup
      - run:
          name: Make sure to use OS X in CircleCI Web UI
          command: |
            if [[ "$OSTYPE" != "darwin"* ]]; then
              echo "Must set option to use OS X in CircleCI Web UI" && exit 1;
            fi
      - run: sudo systemsetup -settimezone 'GMT'
      - run:
          name: Installing cmake
          command: brew install cmake || brew install cmake
      - checkout
      - run:
          name: Build in Debug mode
          environment:
            VERBOSE: 1
          #     Building only the C++ library and unit_test executables.
          command: |
            mkdir -p build/scripts
            cd build/scripts
            cmake -DCMAKE_BUILD_TYPE=Debug  ../..
            make -j2 | grep -v -F '\\-\\- Installing:'
            make install 2>&1 | grep -v -F 'Installing:'
      - run:
          name: Test in Debug mode
          environment:
            VERBOSE: 1
          command: |
            cd ./build/Debug/bin
            ./unit_tests 
  
  
  
  # job: Mac OS/X raw ("build-release"). This job builds in Release mode, used for Python tests & for providing OSX binary release. 
  osx-build-release:
    macos:
      xcode: '11.0.0'
    working_directory: ~/numenta/htm.core
    parallelism: 1
    environment:
      XCODE_SCHEME: htm
      XCODE_WORKSPACE: htm
      ARCHFLAGS: -arch x86_64
    steps:
      # Machine Setup
      - run:
          name: Make sure to use OS X in CircleCI Web UI
          command: |
            if [[ "$OSTYPE" != "darwin"* ]]; then
              echo "Must set option to use OS X in CircleCI Web UI" && exit 1;
            fi
      - run: sudo systemsetup -settimezone 'GMT'
      - run:
          name: Restoring system python
          command: |
            echo 'default to python3' && rm /usr/local/bin/python && ln -s /usr/local/bin/python3 /usr/local/bin/python
            echo 'python version: ' && python --version
            echo 'pip version: ' && python -m pip --version
      - run:
          name: Installing cmake
          command: brew install cmake || brew install cmake
      - checkout
      # Dependencies
      # Restore the dependency cache
      #      - restore_cache:
      #    keys:
      #    # This branch if available
      #    - v1-dep-{{ .Branch }}-
      #    # Default branch if not
      #    - v1-dep-master-
      #    # Any branch if there are none on the default branch - this should be
      #    # unnecessary if you have your default branch configured correctly
      #    - v1-dep-
      - run:
          name: Installing python dependencies
          command: |
            python -m pip install --user --upgrade pip setuptools setuptools-scm wheel
            python -m pip install --no-cache-dir --user -r bindings/py/packaging/requirements.txt  --verbose || exit
      # Save dependency cache
      #      - save_cache:
      #    key: v1-dep-{{ .Branch }}-{{ epoch }}
      #    paths:
      #    # This is a broad list of cache paths to include many possible
      #    # development environments.
      #    - vendor/bundle
      #    - ~/virtualenvs
      #    - ~/.m2
      #    - ~/.ivy2
      #    - ~/.bundle
      #    - ~/.go_workspace
      #    - ~/.gradle
      #    - ~/.cache/bower


      # Build Release with python
      - run:
          name: Build in Release mode
          environment:
              VERBOSE: 1
          command: |
              python setup.py install --user  --prefix=
 
      # Test, run python unit test scripts
      - run:
          name: Running python tests
          command: python setup.py test
      - store_test_results:
          path: tests

      - run:
          name: Package Binary release for OSX
          command: |
            python setup.py bdist_wheel
            cd build/scripts
            make package
            # save artifacts so you can see them with circleCI web site
            mkdir -p /tmp/uploads
            cp -a *.tar.gz /tmp/uploads

      # API for storing and downloading artifacts to/from CI:
      # https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: /tmp/uploads

      # keep the artifacts around for the osx-deploy job
      # in case this is a tagged master build.
      - persist_to_workspace:
          root: build/scripts
          paths: "*.tar.gz"

  # job: Mac OS/X tagged master, deply to GitHub Releases
  #
  # This will need a GitHub Deploy key with write permissions $GITHUB_TOKEN
  # See https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key
  #
  osx-deploy-github:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./build/scripts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/itchio/gothub
            echo "Release version: $CIRCLE_TAG"
            
            cd build/scripts
            for file in ./*.tar.gz ; do
              if [ -e "$file" ] ; then  # check if file exists.
                 export GITHUB_USER="htm-community"
                 export GITHUB_REPO="htm.core"
                 gothub upload --tag $CIRCLE_TAG --name "$file" --file "$file" --replace 
              fi
            done


  # job: Mac OS/X tagged master, deply to GitHub Releases and PYPI
  # https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/?gclid=Cj0KCQjwwIPrBRCJARIsAFlVT8-k1HNsdMJnCg3waIhxjgVOdcGEerQviERJm5qUnQNWppPGOIhgnNQaAk21EALw_wcB
  # Note: uses $PYPI_PASSWORD 
  #
  osx-deploy-pypi:
    docker:
      - image: circleci/python:3.6.4 
    steps:
      - attach_workspace:
          at: ./build/scripts
      - run:
          name: "Publish Release on PYPI"
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --user twine
            cd build/scripts
            mkdir artifact
            for file in ./*.tar.gz ; do
              if [ -e "$file" ] ; then  # check if file exists.
                 # extract the wheel from the github package
                 cd artifact
                 tar -xf ../$file
                 cp */py/*.whl ..
                 cd ..
               fi
             done
             export TWINE_REPOSITORY_URL = "https://test.pypi.org/legacy/"  # test server
             export TWINE_USERNAME="__token__"   # token for PYPI test account for David Keeney.  Not for production
             export TWINE_PASSWORD="pypi-AgENdGVzdC5weXBpLm9yZwIkOTk0YmZjNGYtZTgxNS00Yjk2LTg5ZTAtODE1MGI4MjZhNGZlAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiDXJOuxvodsEDoD5dOH-e0td1DdUSwrl2NCl_lP_vy6RA"
             twine upload --skip-existing --verbose ./*.whl

            



  # job: ARM64 via Docker + QEMU ("arm64-build-test")
  arm64-build-test:
    parallelism: 1
    docker:
      # CircleCI base Debian 10 Buster with remote Docker access, etc.
      #   https://circleci.com/docs/2.0/circleci-images/#buildpack-deps
      - image: circleci/buildpack-deps:buster
    steps:
      - run:
          # This is for local test builds using the CircleCI terminal app.
          #   Local Docker seems to use sudo, CircleCI Docker does not.
          command: |
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              echo "This is a local build. Enabling sudo for docker"
              echo 'export CI_SUDO="sudo"' >> $BASH_ENV
            else
              echo 'export CI_SUDO=' >> $BASH_ENV
            fi
            source $BASH_ENV
      - run: sudo apt-get -y install qemu-system
      - checkout
      - setup_remote_docker  # access circleci's custom docker service
      # make circleci x86_64/amd64 hardware think it's arm64 via docker+qemu
      - run: $CI_SUDO docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Running docker build on ARM64
          command: $CI_SUDO docker build -t htm-arm64-docker --build-arg arch=arm64 .
          no_output_timeout: 2h

workflows:
  version: 2

  osx-build-test: #runs on each commit
    jobs:
      - osx-build-debug    # Mac OS/X raw ("build-debug")
      - osx-build-release  # Mac OS/X raw ("build-release")
          requires:
            - osx-build-debug # all C++ debug tests must pass before Release (and thus artifact) is created

      - osx-deploy-github:
          requires:
            - osx-build-release
          filters:
            # ignore on any commit on any branch by default
            branches:
              ignore: /.*/
            # But act on tagged events
            tags:
              only: /^v.*/
              
      - osx-deploy-pypi:
          requires:
            - osx-build-release
          filters:
            # ignore on any commit on any branch by default
            branches:
              ignore: /.*/
            # But act on tagged events
            tags:
              only: /^v.*/

  nightly: # build and tests taking long time (currecntly ARM64 build ~5hrs), runs only once a day
    triggers:
      - schedule:
          cron: "6 0 * * *" # 6am UTC every day
          filters:
            branches:
              only:
                - master
    jobs:
      - arm64-build-test  # ARM64 docker/qemu ("arm64-build-test")
