name: arm64-build

on:
  # run every day of the week at 06:00
  schedule:
    - cron: 0 6 * * *

jobs:
  build-arm64-docker:
    name: Build for ARM64 on Docker
    runs-on: ubuntu-18.04
    steps:
    - name: Install docker
      run: |
        # bug in ubuntu, conflicts with docker.io
        sudo apt-get update
        sudo apt-get remove --purge -y moby-engine moby-cli
        sudo apt-get install -y docker.io

    - uses: actions/checkout@v1

    - name: ARM64 build
      run: |
        sudo docker build -t htm-arm64-docker --build-arg arch=arm64 .

    - name: Example switch to docker env
      run: |
        sudo docker run -it htm-arm64-docker
        uname -a && echo "\nHello from ARM64 htm.core build!\n"
        exit

    - name: Copy files from docker
      run: |
        sudo docker cp `sudo docker ps -alq`:/usr/local/src/htm.core/dist dist
        ls dist
        


