name: pypi
# Releases to PyPI of htm.core package

on:
  push:
    tags:
      - 'v*.*.*' # vX.Y.Z release tag
  # run on pull_request events that target the master branch
  pull_request: #FIXME remove before merging, only for testing here
    branches:
    - master
      
jobs:
  publish-pypi:
    name: Publish package to PYPI
    needs:
      build
      build-debug
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@master

    - name: Set up Python 3.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.4

    - uses: actions/download-artifact@master
      with:
        name: dist-ubuntu-18.04
        path: dist/

    - uses: actions/download-artifact@master
      with:
        name: dist-macOs-latest
        path: dist/

    - uses: actions/download-artifact@master
      with:
        name: dist-windows-2019
        path: dist/

    - name: pre-PyPI
      #copy dist data to /dist, where PyPI Action expects it
      run: |
        cd dist
        mv `ls -1 htm*-linux_*.whl` `ls -1 htm*-linux_*.whl | sed -e's/linux/manylinux1/'` #rename to manylinux1 to make PYPI accept the package
        rm *.egg #remove obsoleted egg format
        rm requirements.txt # PIPY upload has problem with non-*.whl files 
        cd ..
        ls dist/

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        repository_url: https://test.pypi.org/legacy/ #TODO rm for real pypi


